# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hO_FUEObyXeg0P5PwkT68tYf6x7pHEIJ

# **Praktikumsblatt** - **Python**
 EMAM Wintersemester 2025/2026

Stela Mataj
11530918

# Aufgabe 3
"""

def summe_naiv(n):
    s = 0
    for i in range(1, n + 1):
        s += i
    return s

"""# Aufgabe 4"""

import time
import matplotlib.pyplot as plt

def summe_naiv(n):
    s = 0
    for i in range(1, n + 1):
        s += i
    return s

ns = [10**k for k in range(1, 7)]
zeiten = []

for n in ns:
    start = time.time()
    summe_naiv(n)
    ende = time.time()
    zeiten.append(ende - start)

plt.plot(ns, zeiten, marker="o")
plt.xlabel("n")
plt.ylabel("Laufzeit (Sekunden)")
plt.title("Laufzeit der naiven Summenfunktion")
plt.xscale("log")
plt.yscale("log")
plt.show()

"""# Aufgabe 5"""

import time
import matplotlib.pyplot as plt

def doppelte_summe(n):
    s = 0
    for i in range(1, n + 1):
        for j in range(1, i + 1):
            s += j
    return s

# Verschiedene Werte für n
ns = [100, 200, 400, 600, 800, 1000]
zeiten = []

for n in ns:
    start = time.time()
    doppelte_summe(n)
    ende = time.time()
    zeiten.append(ende - start)

# Darstellung
plt.plot(ns, zeiten, marker="o")
plt.xlabel("n")
plt.ylabel("Laufzeit in Sekunden")
plt.title("Laufzeit der doppelten Summe")
plt.grid(True)
plt.show()

"""# Aufgabe 6"""

def fib_iter(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

print(fib_iter(10))
print(fib_iter(100))

"""# Aufgabe 7"""

def collatz(n):
    folge = [n]

    while n != 1:
        if n % 2 == 0:      # n ist gerade
            n = n // 2
        else:               # n ist ungerade
            n = 3 * n + 1
        folge.append(n)

    return folge

startwerte = [6, 11, 19, 27]

for n in startwerte:
    f = collatz(n)
    print(f"Startwert {n}:")
    print(f"  Folge: {f}")
    print(f"  Länge der Folge: {len(f)}\n")